# Generated by Django 5.1.7 on 2025-04-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0003_alter_media_type_media'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='ModelA',
        ),
        migrations.RenameModel(
            old_name='BoardGame',
            new_name='ModelB',
        ),
        migrations.DeleteModel(
            name='Emprunt',
        ),
    ]
