# Generated by Django 5.1.7 on 2025-04-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0005_media_delete_modela_cd_dvd_livre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='dateEmprunt',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='dateEmprunt',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='dateEmprunt',
        ),
        migrations.RemoveField(
            model_name='media',
            name='date_sortie',
        ),
        migrations.AddField(
            model_name='livre',
            name='editeur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cd',
            name='artiste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='realisateur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
