# Generated by Django 5.1.7 on 2025-04-04 13:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0006_remove_cd_dateemprunt_remove_dvd_dateemprunt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('bloque', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cd',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='disponible',
        ),
        migrations.AddField(
            model_name='media',
            name='date_emprunt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('cd_emprunte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire.cd')),
                ('dvd_emprunte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire.dvd')),
                ('livre_emprunte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire.livre')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire.membre')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='emprunter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliothecaire.emprunteur'),
        ),
    ]
