# Generated by Django 5.1.7 on 2025-04-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0007_emprunteur_remove_cd_disponible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='cd_emprunte',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='dvd_emprunte',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='livre_emprunte',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='media',
            name='emprunter',
        ),
        migrations.DeleteModel(
            name='ModelB',
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Média', 'verbose_name_plural': 'Médias'},
        ),
        migrations.RemoveField(
            model_name='livre',
            name='editeur',
        ),
        migrations.RemoveField(
            model_name='media',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='media',
            name='disponible',
        ),
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='est_empruntable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='titre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Emprunt',
        ),
        migrations.DeleteModel(
            name='Emprunteur',
        ),
    ]
