# Generated by Django 5.1.7 on 2025-04-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0008_jeudeplateau_remove_emprunt_cd_emprunte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliothecaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
