# Generated by Django 5.1.7 on 2025-04-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0009_bibliothecaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeudeplateau',
            name='titre',
        ),
    ]
