# Generated by Django 5.1.7 on 2025-04-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0010_remove_jeudeplateau_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_inscription',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
