# Generated by Django 5.1.7 on 2025-04-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0011_membre_prenom_alter_membre_date_inscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='prenom',
        ),
    ]
