# Generated by Django 5.1.7 on 2025-04-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0012_remove_membre_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='est_empruntable',
        ),
        migrations.AddField(
            model_name='media',
            name='emprunte',
            field=models.BooleanField(default=False),
        ),
    ]
