# Generated by Django 5.1.7 on 2025-04-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0016_remove_emprunt_retourne_alter_emprunt_membre'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='est_retourne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jeudeplateau',
            name='titre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
