# Generated by Django 5.1.7 on 2025-04-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0017_emprunt_est_retourne_jeudeplateau_titre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={},
        ),
        migrations.RemoveField(
            model_name='jeudeplateau',
            name='description',
        ),
        migrations.RemoveField(
            model_name='media',
            name='description',
        ),
        migrations.AddField(
            model_name='jeudeplateau',
            name='auteur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jeudeplateau',
            name='emprunte',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jeudeplateau',
            name='titre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='titre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
