# Generated by Django 5.1.7 on 2025-04-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0018_alter_media_options_remove_jeudeplateau_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='media_ptr',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='media_ptr',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='media',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='membre',
        ),
        migrations.DeleteModel(
            name='JeuDePlateau',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='media_ptr',
        ),
        migrations.DeleteModel(
            name='CD',
        ),
        migrations.DeleteModel(
            name='DVD',
        ),
        migrations.DeleteModel(
            name='Emprunt',
        ),
        migrations.DeleteModel(
            name='Livre',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
