# Generated by Django 5.1.7 on 2025-04-17 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0019_remove_cd_media_ptr_remove_dvd_media_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('disponible', models.BooleanField(default=True)),
                ('artiste', models.CharField(max_length=100)),
                ('duree', models.DurationField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('disponible', models.BooleanField(default=True)),
                ('realisateur', models.CharField(max_length=100)),
                ('duree', models.DurationField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('age_minimum', models.PositiveIntegerField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('disponible', models.BooleanField(default=True)),
                ('auteur', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour', models.DateField()),
                ('cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire.cd')),
                ('dvd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire.dvd')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire.membre')),
                ('livre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire.livre')),
            ],
        ),
    ]
