# Generated by Django 5.1.7 on 2025-04-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0020_cd_dvd_jeudeplateau_livre_emprunt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='jeudeplateau',
            name='age_minimum',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='isbn',
        ),
        migrations.AddField(
            model_name='jeudeplateau',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cd',
            name='artiste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cd',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='realisateur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jeudeplateau',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
