# Generated by Django 5.1.7 on 2025-04-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0021_remove_cd_duree_remove_dvd_duree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='date_emprunt',
        ),
        migrations.RemoveField(
            model_name='jeudeplateau',
            name='disponible',
        ),
    ]
