# Generated by Django 5.1.7 on 2025-04-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0022_remove_emprunt_date_emprunt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='cd',
            name='titre',
        ),
    ]
