# Generated by Django 5.1.7 on 2025-04-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0023_remove_cd_disponible_remove_cd_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cd',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
