# Generated by Django 5.1.7 on 2025-04-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0024_cd_disponible_cd_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvd',
            name='titre',
        ),
        migrations.AddField(
            model_name='dvd',
            name='artiste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
