# Generated by Django 5.1.7 on 2025-04-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0025_remove_dvd_titre_dvd_artiste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dvd',
            old_name='artiste',
            new_name='titre',
        ),
    ]
