# Generated by Django 5.1.7 on 2025-04-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0026_rename_artiste_dvd_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
