# Generated by Django 5.1.7 on 2025-04-20 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0027_alter_livre_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
