# Generated by Django 5.1.7 on 2025-03-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('type_media', models.CharField(choices=[('livre', 'Livre'), ('dvd', 'Dvd'), ('jeu de plateau', 'Jeu de Plateau')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
