# Generated by Django 5.1.7 on 2025-04-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
